test/e2e/e2e.go

1. not to mount the default token, or it will fail in kubeedge
2. wait some time for the pods to be ready not only to be running

e2e: improve e2e test

---

docs/install.md

use separate subnets: service-cluster-ip-range and pod-ip-range.

install: update connector subnets

---

docs/install.md

use unified name of edge-pod-cidr

docs: update install.md

---

pkg/connector/manager.go
pkg/connector/route.go
pkg/connector/tunnel.go

after strongswan is active, connector addis specific routes into table
220 and one aggregated route to edgePODCIDR into main table, which
is propogated into other nodes

connector: add specific routes for remote subnets

---

pkg/connector/iptables.go
pkg/connector/manager.go
pkg/connector/route.go
pkg/connector/watcher.go

to cleanup routes of strongswan before exit

connector: to cleanup routes in table 220

---

pkg/cert/cmd.go

when ca is genarated repeatly, to keep the secret insteading of
update it.

cert: change it to keep secret

---

Makefile
pkg/agent/manager.go
pkg/agent/route.go

in order to co-exist with cni, we add tunnel routes into table 220
with higher priority

agent: add routes to peers

---

deploy/connector.yaml
deploy/helm-chart/templates/connector-deploy.yaml
pkg/connector/manager.go
pkg/connector/tunnel.go
pkg/connector/watcher.go

1) remove tunnel/cert config file in deploy.
2) add watched file back once it is removed.

connector: update deploy file and watch file

---

pkg/connector/tunnel.go

if EdgeNode, we just load the connection and wait;
if Connector, we try to initiate the connection.

connector: handle connection type

---

build/agent/Dockerfile
deploy/operator.yaml
pkg/agent/cni.go
pkg/agent/config.go
pkg/agent/env_prepare.sh
pkg/agent/manager.go
pkg/operator/controllers/agent/agentpodhandler.go
pkg/operator/controllers/agent/agentpodhandler_test.go
pkg/operator/controllers/agent/controller.go
pkg/operator/options.go

1. agent support CNI plugins config format and add portmap and bandwith in config;
2. support edge node pods hairpinMode settings;

support hairpin mode and change CNI plugins configuration

---

pkg/connector/iptables.go

This reverts commit 82366676ae48fecd13ffe5f49b3d777fe10d5c73.

Revert "connector: use return instead of accept in iptables"

---

test/e2e/README.md
test/e2e/cluster.go
test/e2e/e2e.go
test/e2e/framework/test_context.go
test/e2e/framework/util.go
test/e2e/pod.go
test/e2e/scripts/e2e.sh
test/e2e/service.go
test/e2e/util.go

add multi cluster e2e-test and e2e markdown

support multi cluster e2e test

---

pkg/agent/manager.go
pkg/tunnel/strongswan/strongswan.go

1. skip loading connection if nothing changes
2. No builtin automatic SA start, let connector and agent initiate SA if needed.

Improve strongswan manager

---

docs/install.md

Signed-off-by: genghaotao <genghaotao@beyondcent.com>

docs: update installation guide

---

docs/install.md
docs/install_zh.md

Signed-off-by: wangtao <wangtao_yzj@beyondcent.com>

docs: update path of the install.sh

---

MAINTAINERS.md

Signed-off-by: genghaotao <genghaotao@beyondcent.com>

docs: add maintainers.md

---

build/agent/Dockerfile
build/cloud-agent/Dockerfile
build/connector/Dockerfile
deploy/operator.yaml
pkg/agent/config.go
pkg/agent/manager.go
pkg/agent/route.go
pkg/cloud-agent/iptables.go
pkg/connector/iptables.go
pkg/connector/manager.go
pkg/connector/routing/calico.go
pkg/connector/routing/flannel.go
pkg/connector/routing/routing.go
pkg/operator/allocator/allocator.go
pkg/operator/allocator/allocator_test.go
pkg/operator/controllers/agent/controller.go
pkg/operator/controllers/agent/podcidrshandler.go
pkg/operator/controllers/agent/podcidrshandler_test.go
pkg/operator/controllers/connector/controller.go
pkg/operator/controllers/connector/controller_test.go
pkg/operator/options.go
pkg/util/ipset/ipset.go
pkg/util/net/net.go
pkg/util/node/nodeutil.go
pkg/util/route/route.go
third_party/ipset/ipset.go

1. operator: allocator of edge pod cidr and internal IPs of node support dual stack
2. connector、agent、cloud-agent: support dual stack ipset and iptables/ip6tables

Part of the code to support the dual stack protocol

---

docs/design/跨集群服务访问介绍.md

fix ​incorrect syntax 
删除掉多写的“时”字

fix ​incorrect syntax

---

pkg/agent/broadcast.go
pkg/agent/endpoint.go
pkg/agent/iptables.go
pkg/agent/route.go
pkg/cloud-agent/cloud_agent.go

append license header

---

pkg/agent/endpoint.go

agent: fix stale tunnels purging bug

---

docs/get-started.md
docs/get-started_zh.md
docs/manually-install.md
docs/manually-install_zh.md

correct wrong link in documents

---

.github/workflows/main.yml

remove cert-image build from main action

---

pkg/operator/controllers/agent/certhandler.go
pkg/operator/controllers/agent/certhandler_test.go
pkg/operator/controllers/connector/controller.go
pkg/operator/controllers/connector/controller_test.go

operator: add commonName validation for certificates

---

pkg/operator/controllers/proxy/proxy.go
pkg/operator/controllers/proxy/proxy_test.go
pkg/operator/controllers/proxy/types.go

fix wrong realserver port bug

---

test/e2e/cluster.go
test/e2e/e2e.go

e2e: change default ports

---

pkg/agent/manager.go
pkg/connector/routing/routing.go
pkg/util/net/net.go

let agent and connector skip IPv6 route if no IPv6 cidr found

---

pkg/agent/iptables.go

agent: ensure FABEDGE-NAT-OUTGOING chain exists

---

pkg/agent/manager.go
pkg/agent/utils.go
third_party/sysctl/sysctl.go

agent: ensure sysctl parameters are set

---

pkg/agent/iptables.go
pkg/agent/manager.go
pkg/util/ipset/ipset.go

Let endpoint pod at edge node can access itself by domain name

agent: implement nat hairpin

---

pkg/operator/controllers/agent/controller.go
pkg/operator/controllers/agent/controller_test.go
pkg/operator/controllers/community/controller.go
pkg/operator/controllers/community/controller_test.go
pkg/operator/options.go

operator: let community events can generate node events

---

pkg/operator/options.go

fix incorrect cluster-cidrs registry

---

pkg/util/ipset/ipset.go

improve ipset newEntry function

---

pkg/operator/controllers/agent/agentpodhandler.go
pkg/operator/controllers/agent/agentpodhandler_test.go
pkg/operator/controllers/agent/controller.go
pkg/operator/controllers/agent/controller_test.go

fix redundant agent pods problem

---

CHANGELOG/CHANGELOG-0.7.md

Add changelog for v0.7.0

---

README.md
README_zh.md

Add reference to CODE of Conduct in README

---

deploy/crds/fabedge.io_clusters.yaml
pkg/agent/manager.go
pkg/apis/v1alpha1/cluster_types.go
pkg/connector/tunnel.go
pkg/operator/options.go
pkg/tunnel/manager.go
pkg/tunnel/strongswan/strongswan.go

Allow user to specify the public port of connector to avoid possible port conflicts

Implement strongswan port setting

---

pkg/cloud-agent/cloud_agent.go

Issue #386 report that cloud-agent would create hundreds of route table 220 on ubuntu 16, this is because ubuntu 16 allows to create duplicate route table, this commit check if route table 220 exists and ensure only one exists.

Ensure only 220 route table is unique, fix issue #386

---

pkg/cloud-agent/cloud_agent.go
pkg/util/memberlist/memberlist.go

Make cloud-agent no longer quit when it fails to create memberlist, but retry repeatly.

Improve cloud-agent start-up process

---

docs/troubleshooting-guide.md

fix syntax errors in order to make coders read better

fix syntax errors

---

pkg/connector/manager.go

Previous leader election will only execute once, which might lead to no active connector in a cluster after several leader switches.

Fix leader election bug

---

pkg/cloud-agent/cloud_agent.go
pkg/cloud-agent/iptables.go
pkg/connector/iptables.go
pkg/connector/manager.go
pkg/connector/routing/routing.go

Reverts FabEdge/fabedge#415
This PR has been found that might cause unexpected traffic routing.

Revert "Let cloud pod to communicate edge node network"

---

test/e2e/cluster.go
test/e2e/e2e.go
test/e2e/framework/test_context.go
test/e2e/pod.go
test/e2e/service.go

1. Remove useless testcases;
2. Implement pods and services reusage;

Improve e2e test

---

.github/workflows/codeql-analysis.yml
.github/workflows/main.yml
.github/workflows/stale.yml
.github/workflows/sync2gitee.yml
.github/workflows/unittest.yaml

1. Upgrade actions to latest versions;
2. Update schdule of stale action;

Update github actions
