- pkg/operator/controllers/agent/controller.go
- pkg/operator/controllers/agent/controller_test.go
the edge POD state is always **ContainerCreating**.
edgecore service error log
```
E0804 02:52:50.301237   29915 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/host-path/d337f65b-86fc-42b6-8d6a-eb37524d81fa-cni podName:d337f65b-86fc-42b6-8d6a-eb37524d81fa nodeName:}" failed. No retries permitted until 2021-08-04 02:52:50.80113798 +0000 UTC m=+149347.048376094 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"cni\" (UniqueName: \"kubernetes.io/host-path/d337f65b-86fc-42b6-8d6a-eb37524d81fa-cni\") pod \"fabedge-agent-edge\" (UID: \"d337f65b-86fc-42b6-8d6a-eb37524d81fa\") : hostPath type check failed: /etc/cni is not a directory"
... ...
E0805 07:15:15.692826   12800 remote_runtime.go:113] RunPodSandbox from runtime service failed: rpc …
```
> fix: cni config uninitialized for edge pod

- pkg/agent/manager.go
Set up `fabedge-agent  -masq-outgoing=false`
fabedge-agent error logs have been found.
```
kubectl logs -f fabedge-agent-edge1 -c agent -n fabedge
```
Error logs: 
```
I0809 01:47:42.671587       1 manager.go:309] manager "msg"="remove NAT outgoing iptables rules if it exists"  "masqOutgoing"=false
E0809 01:47:42.673575       1 manager.go:140] manager "msg"="failed to configure network" "error"="running [/sbin/iptables -t nat -C POSTROUTING -j fabedge-nat-outgoing --wait]: exit status 2: iptables v1.8.3 (legacy): Couldn't load target `fabedge-nat-outgoing':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\n"  "retryNum"=0
```
> fix:failed to remove NAT outgoing iptables rules

- go.mod
- pkg/common/constants/default.go
- pkg/operator/controllers/agent/controller.go
- pkg/operator/controllers/agent/controller_test.go
In the past, once agent pods were created, they would not be changed
anymore, even arguments or images are changed. Now each agent pod will
have a label "pod-hash", its value is calculated based on pod spec, once
agent controller find that pod-hash is not matched, it will update the pod.
> operator: improve agent pod synchronization

- pkg/operator/controllers/proxy/proxy.go
- pkg/operator/controllers/proxy/proxy_test.go
Sometimes services with no endpoints are left over, which causes a lot of useless ipvs rules on edge node.
> proxy: fix the residual services with no endpoints bug

- Makefile
- deploy/operator.yaml
- pkg/agent/manager.go
- pkg/common/netconf/tunnels.go
- pkg/connector/tunnel.go
- pkg/operator/cmd.go
- pkg/operator/controllers/agent/agentpodhandler.go
- pkg/operator/controllers/agent/agentpodhandler_test.go
- pkg/operator/controllers/agent/confighandler_test.go
- pkg/operator/controllers/agent/controller.go
- pkg/operator/controllers/agent/podcidrshandler_test.go
- pkg/operator/controllers/community/controller_test.go
- pkg/operator/controllers/connector/controller.go
- pkg/operator/controllers/connector/controller_test.go
- pkg/operator/flags.go
- pkg/operator/store/store_test.go
- pkg/operator/types/endpoint.go
- pkg/operator/types/endpoint_test.go
A tunnel endpoint can have multiple addresses as remote or local
addresses and these addresses can also be DNS names. So it's better
and flexible to use addresses instead of IP only.
> Use publicAddresses to replace IP of Tunnel Endpoint

- pkg/agent/env_prepare.sh
- pkg/agent/manager.go
CNI plugin list format needs .conflist suffix to be recognized by k8s
> hotfix:CNI plugin list format needs .conflist suffix to be recognized by k8s

- pkg/agent/config.go
- pkg/agent/manager.go
If agent could not to initiate a tunnel, then it will try and try again,
other tunnels will not have a chance to be loaded and be activated. Even
worse, other routine tasks will not be executed.
> agent: skip errors of add/initiate tunnels

- go.mod
- go.sum
Signed-off-by: Llishiwei <lishiwei@beyondcent.com>
> gomod: update the dependency version of gogo/protobuf to v1.3.2

- deploy/operator.yaml
- pkg/operator/cmd.go
- pkg/operator/controllers/agent/agentpodhandler.go
- pkg/operator/controllers/agent/agentpodhandler_test.go
- pkg/operator/controllers/agent/controller.go
- pkg/operator/options.go
- pkg/operator/types/agent_argument_map.go
- pkg/operator/types/agent_argument_map_test.go
- pkg/operator/types/funcs_test.go
Previously, we use fixed options to configure agent pod arguments.
If agent has new option then we have to add new option to operator.
This is not flexible and extensible, so we changed the way to
configure agent arguments by using enviroment variables.
> operator: provide more flexible way to configure agent pod

- deploy/operator.yaml
- pkg/agent/cmd.go
- pkg/agent/config.go
- pkg/agent/manager.go
- pkg/operator/controllers/agent/agentpodhandler.go
- pkg/operator/controllers/agent/agentpodhandler_test.go
- pkg/operator/controllers/agent/controller.go
- pkg/operator/options.go
- pkg/operator/types/agent_argument_map.go
- pkg/operator/types/agent_argument_map_test.go
For a long time, we had been mistaking allocating PodCIDR
and IPAM. But they are different. We always need IPAM on edge node, but
only need PodCIDR allocation when CNI is calico.
> Remove enable-ipam option from agent

- go.mod
- go.sum
- pkg/agent/service.go
- pkg/common/netconf/tunnels.go
- pkg/operator/controllers/agent/confighandler.go
- pkg/operator/controllers/agent/confighandler_test.go
- pkg/operator/controllers/connector/controller.go
- pkg/operator/controllers/connector/controller_test.go
- pkg/operator/controllers/proxy/load_balance_config_keeper.go
- pkg/operator/controllers/proxy/load_balance_config_keeper_test.go
gopkg.in/yaml.v2 has potential security threat, so upgrade it to v3.
> upgrade gopkg.in/yaml to v3

- pkg/common/constants/default.go
- pkg/operator/controllers/agent/agentpodhandler.go
- pkg/operator/controllers/agent/agentpodhandler_test.go
- pkg/operator/controllers/agent/confighandler.go
- pkg/operator/controllers/proxy/load_balance_config_keeper_test.go
fabedge-agent pods tends to stuck on Pending phase on KubeEdge as
it has some problem with resources using the same name.
> operator: change the naming strategy of fabedge-agent pod

- pkg/operator/options.go
- pkg/tunnel/strongswan/strongswan.go
Sometimes user might provide IPv6 CIDRs in a format which might be not abbreviated enough, e.g. fd96:ee88:0:1::0/116. This can cause CIDR equality check failure because fabedge uses string comparison. By normalize CIDR parameters can avoid this problem.
> Fix IPv6 CIDR equality check failure problem

- pkg/agent/config.go
- pkg/agent/endpoint.go
- pkg/agent/manager.go
- pkg/common/constants/default.go
- pkg/common/netconf/tunnels.go
- pkg/connector/manager.go
- pkg/connector/tunnel.go
- pkg/operator/controllers/agent/certhandler.go
- pkg/operator/controllers/agent/certhandler_test.go
- pkg/operator/controllers/agent/confighandler.go
- pkg/operator/controllers/agent/confighandler_test.go
- pkg/operator/controllers/connector/controller.go
- pkg/operator/controllers/connector/controller_test.go
- pkg/operator/options.go
- pkg/tunnel/manager.go
- pkg/tunnel/strongswan/options.go
- pkg/tunnel/strongswan/strongswan.go
In most cases, edge nodes are located in NAT networks which could be a problem for edge ndoes to establish VPN tunnels. IPSec's mediation feature provide a solution to this situation.
> Implement hold-punching

- pkg/agent/config.go
It's not possible for a client use hostNetwork to visit a service whose endpoints also uses hostNetwork when proxy mode is ipvs, using iptables mode can fix it https://github.com/strongswan/strongswan/discussions/1605.
> Change default proxy mode to iptables

- pkg/agent/manager.go
- pkg/tunnel/manager.go
- pkg/tunnel/strongswan/strongswan.go
Sometimes strongswan will created connection which is stucked queued state when it's mediator is not online, it's helpful to check mediator's state before initiate normal connection.
> Improve strongswan connection initialization

- build/agent/Dockerfile
- build/agent/entrypoint.sh
- build/base-image/Dockerfile
- build/base-image/README.md
- build/cloud-agent/Dockerfile
- build/connector/Dockerfile
- build/connector/entrypoint.sh
For a long time, images of agent, connector and cloud-agent uses iptables-legacy to configure rules, but some OS uses iptables-nft which might cause these component to misfunction, use iptables-wrapper can fix this problem.
> Use iptables-wrapper and change base image

- docs/manually-install.md
- docs/manually-install_zh.md
Avoid the "CrashLoopBackOff" error of the fabedge-connector if the "clusterCIDR" is not configured.
Related log is like:
`cmd.go:53] agent "msg"="invalid arguments found" "error"="cluster-cidr is needed"`
> Update manually-install documents.

- pkg/cloud-agent/cloud_agent.go
- pkg/util/memberlist/memberlist.go
Sometimes cloud-agent migth lose connection to connectors, in this suitation, cloud-agent need to rejoin connectors, otherwise they will no longer receive any data.
> Let cloud-agent rejoin connectors

- pkg/agent/config.go
- pkg/agent/iptables.go
- pkg/agent/manager.go
- pkg/cloud-agent/cloud_agent.go
- pkg/cloud-agent/iptables.go
- pkg/connector/iptables.go
- pkg/connector/manager.go
- pkg/util/ipset/ipset.go
- pkg/util/iptables/iptables.go
Use new template-based iptables helper to maintain rules.
> Improved iptables-helper

- pkg/agent/iptables.go
- pkg/agent/manager.go
- pkg/cloud-agent/iptables.go
- pkg/connector/iptables.go
- pkg/util/ipset/ipset.go
It's better to use Remote and Local rather than Cloud and Edge to orangize ipsets because in multi-clusters enviroment, connector will put CIDR of other clusters in edge ipset, this is confusing.
> Let agent, cloud-agent, connector use the same ipset names
